icons_format = "{icon}"

[theme]
theme = "nord-dark"

[icons]
icons = "awesome5"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "

[[block]]
block = "music"
format = " $icon $volume_icon $combo $play $next| "
seek_step_secs = 10
[[block.click]]
button = "up"
action = "volume_up"
[[block.click]]
button = "down"
action = "volume_down"
[[block.click]]
button = "forward"
action = "seek_forward"
[[block.click]]
button = "back"
action = "seek_backward"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "nvidia_gpu"
interval = 1
format = " $icon GPU $utilization $temperature $clocks "

[[block]]
block = "net"
device = "wlp4s0"
format = " $icon $signal_strength $ssid $frequency"

[[block]]
block = "net"
device = "julio_arch"
format = " $icon Wireguard  $graph_down $graph_up "

[[block]]
block = "time"
interval = 60

